# Generated by Django 4.1 on 2022-08-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Введите дату смерти', null=True, verbose_name='Дата смерти'),
        ),
    ]
