# Generated by Django 4.1 on 2022-08-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, help_text='Введите дату рождения', null=True, verbose_name='Дата рождения'),
        ),
    ]
