# Generated by Django 4.1 on 2022-08-31 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalog_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'автора', 'verbose_name_plural': 'авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'книгу', 'verbose_name_plural': 'книги'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'язык книги', 'verbose_name_plural': 'языки книг'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'статус', 'verbose_name_plural': 'статус'},
        ),
        migrations.AlterModelTable(
            name='catalog',
            table='каталог',
        ),
    ]
